name: dbt-full--refresh
on:
  workflow_dispatch:
    inputs:
      model_name:
        description: "Model name that you want to full-refresh"
        required: true
        default: ""
      
      is_full_refresh:
        description: "Whether to perform a full refresh"
        required: true
        type: boolean
        default: true
      
      profile:
        description: "Profile to use for dbt"
        required: true
        default: "production"

jobs:
  dbt-full-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup-python-3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10

      - name: install-requirements
        working-directory: ./dagger
        run: |
          pip install -r requirements.txt
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.12.4 sh   

      - name: dbt full refresh
        working-directory: ./dagger/src/main
        run: |
          python _dbt_dagger.py
        env:
          MODEL_NAME: ${{ inputs.model_name }}
          IS_FULL_REFRESH: ${{ inputs.is_full_refresh }}
          PROFILE: ${{ inputs.profile }}
