name: dagger example
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true
        default: ""

jobs:
  dagger_example:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup-python-3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10

      - name: install-requirements
        working-directory: ./dagger
        run: |
          pip install -r requirements.txt
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.12.4 sh   

      - name: dbt full refresh
        working-directory: ./dagger/src/main
        run: |
          dagger call hello --name= ${{ inputs.name }}