name: dagger example
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true
        default: ""

jobs:
  dagger_example:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: install-requirements
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.12.4 sh
          sudo mv ~/bin/dagger /usr/local/bin/

      - name: run example
        run: |
          dagger call hello --name=${{ inputs.name }}